In [36]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn import datasets

In [37]:
dataset = datasets.load_iris()
X = dataset.data[:, :4]
y = dataset.target

In [38]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

In [39]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [40]:
classifier = BernoulliNB()
classifier.fit(X_train, y_train)

BernoulliNB()

In [41]:
y_pred = classifier.predict(X_test)

In [42]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[11  0  0]
 [ 1  4  8]
 [ 0  2  4]]


In [43]:
print(cm)
TP = np.diag(cm)
FP = cm.sum(axis = 0) - np.diag(cm)
FN = cm.sum(axis = 1) - np.diag(cm)
TN = cm.sum()-(FP + FN + TP)
print(TP[0], FP[0], FN[0], TN[0])

[[11  0  0]
 [ 1  4  8]
 [ 0  2  4]]
11 1 0 18


In [44]:
ACC = (TP + TN)/(TP+TN+FP+FN)
ACC[0]

0.9666666666666667

In [45]:
PRC = TP/(TP+FP)
PRC[0]

0.9166666666666666

In [46]:
RCL = TP/(TP+FN)
RCL[0]

1.0